#!/usr/bin/env python
# -- coding: utf-8 --

import os

#os.system(project_name = input("project name to create ? : "))
project_name = input("project name to create ? : ")

os.system(f"mkdir {project_name}")
os.system(f"cd {project_name}")

os.system(f"touch requirements.txt")
os.system(f"touch setup.py")
os.system(f"mkdir -p '{project_name}/notebooks/data'")
os.system(f"touch {project_name}/init.py")
os.system(f"mkdir scripts")
os.system(f"touch scripts/start_project.py")
